### ISSUE TITLE
Get announcement from txt

### ISSUE THREAD

**Issue by Jymapas** [Jymapas/WeekChgkSPBParser#4]
Получить данные из .txt файла.

Да, я не умею работать с файлами.

**Comment by FA72** [comment]
Довольно просто, на самом деле. 
https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/file-system/how-to-read-from-a-text-file - вот.
https://github.com/FA72/TgKarBot/commit/15f03c3a842f936ce62caedafbf7a6e887fa09ce - здесь можешь посмотреть, как я с этим ебался для того бота, до того, как сделал БД

**Comment by Jymapas** [comment]
Реализовал всё в feature/3_parseCommand
